### ISSUE TITLE
Code block highlight line breaks on small screen

### ISSUE THREAD

**Issue by al-imam** [radix-ui/website#732]
### Current Behavior
The highlighted line does not expand to fill the entire width when the code block overflows.

![Screenshot_20231229_103703](https://github.com/radix-ui/website/assets/45687883/1d6a47ec-9846-47b8-81a8-1bdde7e3c526)

### Expected behavior

![Screenshot_20231229_111301](https://github.com/radix-ui/website/assets/45687883/ce460302-5b8b-462f-aa97-79396e3a2f38)

### Suggested solution
As a junior developer, I discovered a solution. I am unsure if there are any side effects, but I found that adding `min-width: 100%;` and changing `display: block;` to `display: inline-block;` worked.

```css
 /* components/Pre.module.css */

.Pre > code {
  /* display: block; */
  display: inline-block;
  min-width: 100%;
}
```

**Thank you**
